package dev.everydaythings.graph.language;

import com.ibm.icu.util.ULocale;
import dev.everydaythings.graph.Seed;
import dev.everydaythings.graph.datum.Binding;
import dev.everydaythings.graph.datum.Frame;
import dev.everydaythings.graph.id.CompoundKey;
import dev.everydaythings.graph.id.ItemRef;
import dev.everydaythings.graph.item.Item;
import dev.everydaythings.graph.library.index.TokenPosting;
import dev.everydaythings.graph.runtime.librarian.Librarian;
import dev.everydaythings.graph.text.FrameMap;
import dev.everydaythings.graph.text.FrameMap.BindingMap;
import dev.everydaythings.graph.text.FrameMap.Part;
import dev.everydaythings.graph.text.ParseContext;
import dev.everydaythings.graph.text.ParseParams;
import dev.everydaythings.graph.text.TextSpan;
import dev.everydaythings.graph.text.TokenLattice;
import dev.everydaythings.graph.text.TokenLattice.TokenSpan;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * English — the first natural language to land in CG (ISO 639-3 code "eng").
 * Singleton Language item; behavioral code lives here, the bulk lexicon (synsets,
 * lexemes, glosses, irregular morphology) is generated by
 * {@code :imports:languages:english} and published into the graph as signed
 * frames that any Librarian fetches on demand.
 *
 * <p>Canonical key matches the {@link Language.English} static-key holder in
 * {@code :core} so that {@code @Seed.Binding(qualifiers = {Language.English.KEY})}
 * across the codebase points at this Language item.
 *
 * <p>Grammar coverage so far is the <b>transitive-verb pattern</b>: a verb whose
 * direct object fills THEME, plus oblique PPs whose preposition assigns its
 * object to a thematic role via the role item's own English Preposition Lexeme.
 * "add 5 to 3" parses to ADD{THEME=5, GOAL=3} and renders the symmetric way.
 *
 * <p>The lexicon is structured around <b>lexemes on their semantic homes</b>:
 * verb-lemmas live on predicate items (Add carries "add"/"sum"); preposition
 * lemmas live on thematic-role items (Goal carries "to"; Source carries "from").
 * Surface-form → semantic mapping is symmetric in both directions.
 *
 * <p>Sub-Languages for regional variants (English-US, English-GB, English-AU,
 * ...) will extend this class, override {@link #locale()} with their BCP-47
 * locale, and declare regional overrides (color/colour, date format, currency).
 * When a sub-Language doesn't override a behavior, it inherits this base
 * implementation.
 */
@Seed.Item(key = Language.English.KEY, head = Language.KEY)
@Seed.Embodies(key = Language.English.KEY)
public class English extends Language {

    public English(ItemRef iid) {
        super(iid);
    }

    public English(ItemRef iid, Librarian librarian) {
        super(iid, librarian);
    }

    @Override
    public ULocale locale() {
        return ULocale.ENGLISH;
    }

    // ==================================================================================
    // Render — frame → English prose
    // ==================================================================================

    /**
     * Render a frame as English prose.
     *
     * <p>Current coverage — the transitive-verb pattern: find an English verb-lemma
     * Lexeme on the predicate; emit the lemma followed by the THEME-rendered text
     * (as direct object); for every other binding, find the English preposition
     * lemma declared on the role item itself, and emit {@code <prep> <target-rendered>}.
     * So ADD{THEME=5, GOAL=3} becomes "add 5 to 3".
     *
     * <p>When the predicate carries no English verb-lemma, returns the input
     * unchanged so a different Language in the stack can take a turn.
     */
    @Override
    public FrameMap render(FrameMap frameMap, ParseParams params) {
        if (frameMap == null
                || frameMap.predicate() == null
                || frameMap.predicate().value() == null
                || librarian() == null) {
            return frameMap;
        }
        ItemRef predicateIid = frameMap.predicate().value().iid();
        Optional<String> verbLemma = findEnglishVerbLemma(predicateIid);
        if (verbLemma.isEmpty()) return frameMap;

        BindingMap themeBinding = null;
        List<BindingMap> obliques = new ArrayList<>();
        ItemRef themeRole = ItemRef.iid(ThematicRole.Theme.KEY);
        for (BindingMap b : frameMap.bindings()) {
            if (b.role() == null || b.role().value() == null) continue;
            if (themeRole.equals(b.role().value().iid())) {
                themeBinding = b;
            } else {
                obliques.add(b);
            }
        }
        if (themeBinding == null) return frameMap;

        StringBuilder sb = new StringBuilder();
        sb.append(verbLemma.get());
        sb.append(' ').append(renderTarget(themeBinding.target().value(), params));
        for (BindingMap obl : obliques) {
            ItemRef roleIid = obl.role().value().iid();
            Optional<String> prep = findEnglishPrepositionLemma(roleIid);
            if (prep.isEmpty()) continue;
            sb.append(' ').append(prep.get());
            sb.append(' ').append(renderTarget(obl.target().value(), params));
        }
        return frameMap.withText(sb.toString());
    }

    // ==================================================================================
    // Parse — English prose → frame contribution
    // ==================================================================================

    /**
     * Recognize the transitive-verb pattern in the token stream and emit a frame.
     *
     * <p>Scans for the <b>first</b> token whose dictionary postings reveal an
     * English verb-lemma — that token's posting target is the predicate. The
     * <b>next</b> token (when not itself a preposition) fills THEME as the
     * direct object. Then it walks {@code <preposition> <operand>} pairs;
     * each preposition's posting target is the thematic role it marks, and the
     * following operand becomes that role's binding target.
     *
     * <p>Operand resolution: LITERAL tokens parse as {@code Long}; WORD tokens
     * resolve to the first posting's target ItemRef (so proper nouns and item
     * references work uniformly with literals).
     *
     * <p>Returns an empty FrameMap when no English verb-lemma is found —
     * yielding to other Languages in the consensus round.
     */
    @Override
    public FrameMap parse(ParseContext ctx) {
        List<TokenSpan> tokens = ctx.tokens();
        if (tokens == null || tokens.isEmpty() || librarian() == null) {
            return FrameMap.empty();
        }

        // 1. Find the predicate-anchoring verb.
        int verbIdx = -1;
        ItemRef predicateIid = null;
        TextSpan verbSpan = null;
        for (int i = 0; i < tokens.size(); i++) {
            TokenSpan t = tokens.get(i);
            for (TokenPosting p : t.postings()) {
                if (isEnglishVerbLemmaPosting(p) && p.target() != null) {
                    verbIdx = i;
                    predicateIid = p.target();
                    verbSpan = t.span();
                    break;
                }
            }
            if (verbIdx >= 0) break;
        }
        if (verbIdx < 0) return FrameMap.empty();

        BigDecimal predConfidence = new BigDecimal("0.8500");
        BigDecimal bindConfidence = new BigDecimal("0.8000");

        // 2. Walk post-verb tokens building bindings.
        List<BindingMap> bindings = new ArrayList<>();
        int idx = verbIdx + 1;

        // Direct object (THEME) — first non-preposition operand after the verb.
        if (idx < tokens.size() && !isEnglishPrepositionToken(tokens.get(idx))) {
            Object themeVal = operandValue(tokens.get(idx));
            if (themeVal != null) {
                bindings.add(makeBinding(
                        ItemRef.iid(ThematicRole.Theme.KEY),
                        themeVal,
                        tokens.get(idx).span(),
                        bindConfidence));
                idx++;
            }
        }

        // Subsequent oblique PPs — {<preposition> <operand>}* .
        while (idx + 1 < tokens.size()) {
            TokenSpan prepToken = tokens.get(idx);
            ItemRef prepRoleIid = englishPrepositionRole(prepToken);
            if (prepRoleIid == null) { idx++; continue; }

            TokenSpan operandToken = tokens.get(idx + 1);
            Object operandVal = operandValue(operandToken);
            if (operandVal == null) { idx += 2; continue; }

            bindings.add(makeBinding(
                    prepRoleIid,
                    operandVal,
                    operandToken.span(),
                    bindConfidence));
            idx += 2;
        }

        if (bindings.isEmpty()) return FrameMap.empty();

        return new FrameMap(
                null,
                new Part<>(ItemRef.of(predicateIid), predConfidence, List.of(verbSpan)),
                bindings,
                List.of());
    }

    // ==================================================================================
    // Lexeme lookups — render side (Item-fetch by IID, walk endorsed Lexeme frames)
    // ==================================================================================

    /**
     * Find an English verb-lemma string on the predicate item. Picks the first
     * Lexeme frame whose VALUE-binding qualifiers include English + Verb + Lemma.
     */
    private Optional<String> findEnglishVerbLemma(ItemRef predicateIid) {
        return librarian().fetchItem(predicateIid)
                .flatMap(item -> item.endorsedFramesByPredicate(
                                ItemRef.iid(LexicalVocabulary.Lexeme.KEY))
                        .map(frame -> readEnglishVerbLemma(frame))
                        .filter(Optional::isPresent)
                        .map(Optional::get)
                        .findFirst());
    }

    /**
     * Find the English preposition lemma that marks the given thematic role.
     * Looks up the role Item directly and reads its endorsed English-Preposition
     * Lexeme frame. The role's own lexicon declares its surface markers — no
     * separate preposition-Item layer.
     */
    private Optional<String> findEnglishPrepositionLemma(ItemRef roleIid) {
        return librarian().fetchItem(roleIid)
                .flatMap(item -> item.endorsedFramesByPredicate(
                                ItemRef.iid(LexicalVocabulary.Lexeme.KEY))
                        .map(frame -> readEnglishPrepositionLemma(frame))
                        .filter(Optional::isPresent)
                        .map(Optional::get)
                        .findFirst());
    }

    /** Pull an English verb-lemma string from a Lexeme frame (Value + English + Verb + Lemma). */
    private static Optional<String> readEnglishVerbLemma(Frame lexemeFrame) {
        return readLemma(lexemeFrame, ItemRef.iid(PartOfSpeech.Verb.KEY));
    }

    /** Pull an English preposition-lemma string from a Lexeme frame (Value + English + Preposition + Lemma). */
    private static Optional<String> readEnglishPrepositionLemma(Frame lexemeFrame) {
        return readLemma(lexemeFrame, ItemRef.iid(PartOfSpeech.Preposition.KEY));
    }

    /**
     * Generic lemma reader: find the VALUE binding whose qualifiers include
     * English + the given POS + Lemma, and return its String target.
     */
    private static Optional<String> readLemma(Frame lexemeFrame, ItemRef pos) {
        ItemRef valueRole = ItemRef.iid(ThematicRole.Value.KEY);
        ItemRef english = ItemRef.iid(Language.English.KEY);
        ItemRef lemma = ItemRef.iid(GrammaticalFeature.Lemma.KEY);
        return lexemeFrame.bindings()
                .filter(b -> valueRole.equals(b.role()))
                .filter(b -> hasQualifier(b, english)
                        && hasQualifier(b, pos)
                        && hasQualifier(b, lemma))
                .map(b -> b.target() instanceof String s ? s : null)
                .filter(Objects::nonNull)
                .findFirst();
    }

    private static boolean hasQualifier(Binding binding, ItemRef target) {
        for (CompoundKey.Qualifier q : binding.qualifiers()) {
            if (q instanceof CompoundKey.Sememe s && target.equals(s.id())) return true;
        }
        return false;
    }

    // ==================================================================================
    // Token-posting predicates — parse side (read features off TokenPostings produced
    // by the TokenDictionary's index walk over endorsed Lexeme frames).
    // ==================================================================================

    /** A TokenPosting that came from an English verb-lemma Lexeme. */
    private static boolean isEnglishVerbLemmaPosting(TokenPosting p) {
        return isEnglishLexemePosting(p)
                && p.features().contains(ItemRef.iid(PartOfSpeech.Verb.KEY))
                && p.features().contains(ItemRef.iid(GrammaticalFeature.Lemma.KEY));
    }

    /** A TokenPosting that came from an English preposition-lemma Lexeme. */
    private static boolean isEnglishPrepositionLemmaPosting(TokenPosting p) {
        return isEnglishLexemePosting(p)
                && p.features().contains(ItemRef.iid(PartOfSpeech.Preposition.KEY))
                && p.features().contains(ItemRef.iid(GrammaticalFeature.Lemma.KEY));
    }

    /** A TokenPosting whose source is an English-scoped Lexeme frame. */
    private static boolean isEnglishLexemePosting(TokenPosting p) {
        return ItemRef.iid(LexicalVocabulary.Lexeme.KEY).equals(p.predicate())
                && ItemRef.iid(Language.English.KEY).equals(p.scope());
    }

    /** True when any of {@code token}'s postings is an English preposition lemma. */
    private static boolean isEnglishPrepositionToken(TokenSpan token) {
        for (TokenPosting p : token.postings()) {
            if (isEnglishPrepositionLemmaPosting(p)) return true;
        }
        return false;
    }

    /** The role IID a preposition token marks, taken from its English-preposition posting's target. */
    private static ItemRef englishPrepositionRole(TokenSpan token) {
        for (TokenPosting p : token.postings()) {
            if (isEnglishPrepositionLemmaPosting(p)) return p.target();
        }
        return null;
    }

    // ==================================================================================
    // Operand resolution + binding construction
    // ==================================================================================

    /**
     * Convert a token to a binding-target value. LITERAL tokens parse as a
     * {@code Long}; WORD tokens use the first posting's target ItemRef (proper
     * nouns, references). Returns null when the token resolves to nothing useful.
     */
    private static Object operandValue(TokenSpan token) {
        if (token.kind() == TokenLattice.Kind.LITERAL) {
            try {
                return Long.parseLong(token.surfaceText().trim());
            } catch (NumberFormatException e) {
                return null;
            }
        }
        if (!token.postings().isEmpty()) {
            return token.postings().get(0).target();
        }
        return null;
    }

    private static BindingMap makeBinding(ItemRef roleIid, Object target,
                                          TextSpan targetSpan, BigDecimal confidence) {
        return new BindingMap(
                new Part<>(ItemRef.of(roleIid), confidence, List.of()),
                List.of(),
                new Part<>(target, confidence, List.of(targetSpan)));
    }

    /**
     * Render a binding target as English text. Literals (Long, String) format
     * directly; everything else falls back to {@code toString()} for now. A
     * follow-up pass recurses into nested frames via {@link #render}.
     */
    private String renderTarget(Object target, ParseParams params) {
        if (target == null) return "";
        if (target instanceof Long n) return Long.toString(n);
        if (target instanceof String s) return s;
        return target.toString();
    }

    // ==================================================================================
    // Roadmap — natural extensions, ordered by leverage.  Each is a data-layer
    // change (lexicon) or a focused code-layer change; none require rethinking
    // the lexeme-on-its-semantic-home architecture.
    // ==================================================================================
    //
    // PARSE
    //   * Subject-fronted clauses ("Tolkien wrote The Hobbit") — currently parse
    //     assumes the verb is at position 0.  Generalize: a token sequence before
    //     the verb is the AGENT (or EXPERIENCER for psych-verbs).  Requires proper
    //     nouns to surface as NAMEs.
    //   * Polysemy resolution — when a token has multiple postings (e.g., "with"
    //     marks INSTRUMENT and PARTNER), pick by verb's expected roles (declared
    //     elsewhere; VerbNet's subcategorization frames are the right source).
    //   * Multi-word lexemes ("divided by", "in front of") — needs TokenLattice
    //     to surface multi-word spans; once it does, the parser walks them like
    //     single-token prepositions.
    //   * Imperative vs declarative — "add 5 to 3" is imperative (no subject);
    //     "5 added to 3" is passive (THEME first, verb participle, "to"-PP for
    //     GOAL).  Both yield the same frame; the parser needs to recognize both
    //     surface shapes.
    //
    // RENDER
    //   * Recursive sub-frame rendering — {@link #renderTarget} currently falls
    //     to {@code toString()} for anything but Long/String.  For a RefTarget
    //     pointing at a sub-frame, fetch the frame and call {@code render} on it
    //     (mirroring {@link dev.everydaythings.graph.operator.OperatorNotation}'s
    //     recursion).  For an ItemRef pointing at a named entity, walk its
    //     identifier predicates (NAME/TITLE) and emit the surface form.
    //   * Register-aware verb-lemma selection — Add has lemmas "add" and "sum";
    //     today the first one wins by canonical-hash order.  Use {@link ParseParams#register}
    //     to pick (TECHNICAL→"sum", NEUTRAL→"add", CASUAL→whatever).  Same idea
    //     for preposition variants ("to" vs "on" vs "into" on Goal).
    //   * Articles ("the", "a/an") — proper nouns render bare; definite nouns
    //     get "the"; indefinite first-mention gets "a"/"an" (with vowel-onset
    //     "an" agreement).  Salience-aware: {@link ParseParams#salientReferents}
    //     drives the choice.
    //
    // LEXICON
    //   * Multiplicative/divisional prepositions — "multiply X by Y" needs "by"
    //     as an Instrument lexeme (alongside "with").  "divide X by Y" same.
    //     "X times Y" is a coordinator pattern, not preposition — coordination
    //     is its own work item.
    //   * Verb morphology — past, present-participle, third-person-singular.
    //     Most verbs follow regular rules (add-ed, add-ing, add-s); irregulars
    //     come from UniMorph.  Render emits past for narrated frames ("Tolkien
    //     wrote..."); parse normalizes inflected forms back to lemmas.  Blocked
    //     on importer work (task #99) for the data.
    //   * Identifier predicates — NAME / TITLE / SERIAL_NUMBER / ALIAS render as
    //     bare lemma; parse anchors to the named item.  Lives partly in :core
    //     (the predicates) and partly in :languages:english (the English
    //     rendering rules — capitalization conventions, "The"-prefixed titles).
    //
    // ARCHITECTURE
    //   * Sub-Languages — English-US vs English-GB ("color"/"colour", date
    //     formats, currency, "trousers"/"pants").  Each extends English,
    //     overrides {@link #locale()}, and declares regional overrides.
    //   * Confidence calibration — current parse confidence is hand-picked
    //     (0.85 predicate, 0.80 bindings).  Once we have multiple Languages
    //     contributing on the same input, the relative weights matter; they
    //     should reflect how well the surface form fits English grammar
    //     specifically (verb-lemma exact match, all expected-PPs present, no
    //     stray tokens).
}
