package dev.everydaythings.graph.language;

import com.ibm.icu.util.ULocale;
import dev.everydaythings.graph.Seed;
import dev.everydaythings.graph.datum.Binding;
import dev.everydaythings.graph.datum.Frame;
import dev.everydaythings.graph.id.CompoundKey;
import dev.everydaythings.graph.id.ItemRef;
import dev.everydaythings.graph.item.Item;
import dev.everydaythings.graph.runtime.librarian.Librarian;
import dev.everydaythings.graph.text.FrameMap;
import dev.everydaythings.graph.text.FrameMap.BindingMap;
import dev.everydaythings.graph.text.ParseParams;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * English — the first natural language to land in CG (ISO 639-3 code "eng").
 * Singleton Language item; behavioral code lives here, the bulk lexicon (synsets,
 * lexemes, glosses, irregular morphology) is generated by
 * {@code :imports:languages:english} and published into the graph as signed
 * frames that any Librarian fetches on demand.
 *
 * <p>Canonical key matches the {@link Language.English} static-key holder in
 * {@code :core} so that {@code @Seed.Binding(qualifiers = {Language.English.KEY})}
 * across the codebase points at this Language item.
 *
 * <p>Skeleton — locale plumbed in; {@link #render} handles the simplest English
 * grammar pattern, "transitive-verb with oblique PPs", which covers cases like
 * "add 5 to 3" (verb=add, THEME=5, GOAL=3 surfaced via preposition "to"). The
 * verb lemma comes from the predicate's English verb-lemma Lexeme frame; the
 * preposition for each oblique role is looked up via PrepositionVocabulary's
 * AssignedRole declarations. {@link #parse} stays a placeholder until render
 * pins down the lexicon-lookup shape.
 *
 * <p>Sub-Languages for regional variants (English-US, English-GB, English-AU,
 * ...) will extend this class, override {@link #locale()} with their BCP-47
 * locale, and declare regional overrides (color/colour, date format, currency).
 * When a sub-Language doesn't override a behavior, it inherits this base
 * implementation.
 */
@Seed.Item(key = Language.English.KEY, head = Language.KEY)
@Seed.Embodies(key = Language.English.KEY)
public class English extends Language {

    public English(ItemRef iid) {
        super(iid);
    }

    public English(ItemRef iid, Librarian librarian) {
        super(iid, librarian);
    }

    @Override
    public ULocale locale() {
        return ULocale.ENGLISH;
    }

    /**
     * Render a frame as English prose.
     *
     * <p>Current coverage — the transitive-verb pattern: find an English verb-lemma
     * Lexeme on the predicate; emit the lemma followed by the THEME-rendered text
     * (as direct object); for every other binding, find the English preposition
     * that assigns that role via PrepositionVocabulary's AssignedRole declarations,
     * and emit {@code <prep> <target-rendered>}. So ADD{THEME=5, GOAL=3} becomes
     * "add 5 to 3" (verb=add, THEME=5 direct object, GOAL=3 via "to"-PP).
     *
     * <p>When the predicate carries no English verb-lemma, returns the input
     * unchanged so a different Language in the stack can take a turn.
     */
    @Override
    public FrameMap render(FrameMap frameMap, ParseParams params) {
        if (frameMap == null
                || frameMap.predicate() == null
                || frameMap.predicate().value() == null
                || librarian() == null) {
            return frameMap;
        }
        ItemRef predicateIid = frameMap.predicate().value().iid();
        Optional<String> verbLemma = findEnglishVerbLemma(predicateIid);
        if (verbLemma.isEmpty()) return frameMap;

        BindingMap themeBinding = null;
        List<BindingMap> obliques = new ArrayList<>();
        ItemRef themeRole = ItemRef.iid(ThematicRole.Theme.KEY);
        for (BindingMap b : frameMap.bindings()) {
            if (b.role() == null || b.role().value() == null) continue;
            if (themeRole.equals(b.role().value().iid())) {
                themeBinding = b;
            } else {
                obliques.add(b);
            }
        }
        if (themeBinding == null) return frameMap;

        StringBuilder sb = new StringBuilder();
        sb.append(verbLemma.get());
        sb.append(' ').append(renderTarget(themeBinding.target().value(), params));
        for (BindingMap obl : obliques) {
            ItemRef roleIid = obl.role().value().iid();
            Optional<String> prep = findEnglishPrepositionLemma(roleIid);
            if (prep.isEmpty()) continue;
            sb.append(' ').append(prep.get());
            sb.append(' ').append(renderTarget(obl.target().value(), params));
        }
        return frameMap.withText(sb.toString());
    }

    /**
     * Find an English verb-lemma string on the predicate item. Picks the first
     * Lexeme frame whose VALUE-binding qualifiers include English + Verb + Lemma.
     */
    private Optional<String> findEnglishVerbLemma(ItemRef predicateIid) {
        return librarian().fetchItem(predicateIid)
                .flatMap(item -> item.endorsedFramesByPredicate(
                                ItemRef.iid(LexicalVocabulary.Lexeme.KEY))
                        .map(frame -> readEnglishVerbLemma(frame))
                        .filter(Optional::isPresent)
                        .map(Optional::get)
                        .findFirst());
    }

    /**
     * Find the English preposition lemma that marks the given thematic role.
     * Looks up the role Item directly and reads its endorsed English-Preposition
     * Lexeme frame. The role's own lexicon declares its surface markers — no
     * separate preposition-Item layer.
     */
    private Optional<String> findEnglishPrepositionLemma(ItemRef roleIid) {
        return librarian().fetchItem(roleIid)
                .flatMap(item -> item.endorsedFramesByPredicate(
                                ItemRef.iid(LexicalVocabulary.Lexeme.KEY))
                        .map(frame -> readEnglishPrepositionLemma(frame))
                        .filter(Optional::isPresent)
                        .map(Optional::get)
                        .findFirst());
    }

    /**
     * Pull an English verb-lemma string out of a Lexeme frame: matches the
     * VALUE-role binding whose qualifiers include English + Verb + Lemma, with
     * a String target.
     */
    private static Optional<String> readEnglishVerbLemma(Frame lexemeFrame) {
        return readLemma(lexemeFrame,
                ItemRef.iid(PartOfSpeech.Verb.KEY));
    }

    /** Same shape as {@link #readEnglishVerbLemma}, but matches Preposition POS. */
    private static Optional<String> readEnglishPrepositionLemma(Frame lexemeFrame) {
        return readLemma(lexemeFrame,
                ItemRef.iid(PartOfSpeech.Preposition.KEY));
    }

    /**
     * Generic lemma reader: find the VALUE binding whose qualifiers include
     * English + the given POS + Lemma, and return its String target.
     */
    private static Optional<String> readLemma(Frame lexemeFrame, ItemRef pos) {
        ItemRef valueRole = ItemRef.iid(ThematicRole.Value.KEY);
        ItemRef english = ItemRef.iid(Language.English.KEY);
        ItemRef lemma = ItemRef.iid(GrammaticalFeature.Lemma.KEY);
        return lexemeFrame.bindings()
                .filter(b -> valueRole.equals(b.role()))
                .filter(b -> hasQualifier(b, english)
                        && hasQualifier(b, pos)
                        && hasQualifier(b, lemma))
                .map(b -> b.target() instanceof String s ? s : null)
                .filter(Objects::nonNull)
                .findFirst();
    }

    private static boolean hasQualifier(Binding binding, ItemRef target) {
        for (CompoundKey.Qualifier q : binding.qualifiers()) {
            if (q instanceof CompoundKey.Sememe s && target.equals(s.id())) return true;
        }
        return false;
    }

    /**
     * Render a binding target as English text. Literals (Long, String) format
     * directly; everything else falls back to {@code toString()} for now. A
     * follow-up pass recurses into nested frames via {@link #render}.
     */
    private String renderTarget(Object target, ParseParams params) {
        if (target == null) return "";
        if (target instanceof Long n) return Long.toString(n);
        if (target instanceof String s) return s;
        return target.toString();
    }

    // TODO: override parse(ParseContext) — once render proves the shape, parse
    //       follows the same lexeme-driven anchoring path.
}
