rootProject.name = 'common-graph'

include ':core'
include ':bridges'
include ':bridges:tcp'
include ':bridges:http'
include ':bridges:parley'
include ':bridges:noise'
include ':bridges:tls'
include ':bridges:x509'
include ':bridges:keri'
include ':imports'
include ':imports:keyboard'
include ':imports:languages'
include ':imports:languages:english'
include ':languages'
include ':languages:english'
