rootProject.name = 'common-graph'

include ':annotations'
include ':substrate'
include ':library'
include ':core'
include ':bridges'
include ':bridges:tcp'
include ':bridges:unix'
include ':bridges:http'
include ':bridges:tls'
include ':bridges:x509'
include ':bridges:keri'
include ':imports'
include ':imports:keyboard'
include ':imports:languages'
include ':imports:languages:english'
include ':languages'
include ':languages:english'
include ':ui'
include ':ui:tui'
include ':ui:skia'
include ':ui:filament'
